'use client';

import { createContext, useContext, useMemo, useState, useEffect, useCallback } from 'react';

const LANGUAGE_STORAGE_KEY = 'mynd_language';
const LanguageContext = createContext(null);

export const SUPPORTED_LANGUAGES = [
  { code: 'de', label: 'Deutsch' },
  { code: 'en', label: 'English' },
  { code: 'fr', label: 'Français' },
  { code: 'es', label: 'Español' },
  { code: 'it', label: 'Italiano' },
  { code: 'pt', label: 'Português' },
  { code: 'nl', label: 'Nederlands' },
  { code: 'pl', label: 'Polski' },
  { code: 'tr', label: 'Türkçe' },
  { code: 'ru', label: 'Русский' },
  { code: 'ja', label: '日本語' },
  { code: 'zh', label: '中文' }
];

const TRANSLATIONS = {
  de: {
    newChat: 'Neuer Chat',
    settings: 'Einstellungen',
    currentChat: 'Aktueller Chat',
    askHeading: 'Was liegt dir auf dem Herzen?',
    askSubheading: 'Frag mich alles zu deiner Wissensbasis.',
    askPlaceholder: 'Stelle eine Frage...',
    composerPlaceholder: 'Deine Nachricht hier...',
    documentIndexing: 'Dokumenten-Indexierung',
    current: 'Aktuell',
    files: 'Dateien',
    speed: 'Geschwindigkeit',
    elapsed: 'Verstrichen',
    chunks: 'Chunks',
    errors: 'Fehler',
    save: 'Speichern',
    cancel: 'Abbrechen',
    createEvent: 'Termin erstellen',
    saveEvent: 'Speichere...',
    sources: 'Quellen',
    language: 'Sprache',
    theme: 'Theme',
    darkMode: 'Dunkelmodus',
    motionStyle: 'Bewegungsstil',
    motionCalm: 'Ruhig',
    motionDynamic: 'Dynamisch',
    motionAurora: 'Aurora',
    designControlHint: 'Du kannst Design-Optionen direkt hier anpassen:',
    cmdLanguageChanged: 'Sprache wurde auf {value} umgestellt.',
    cmdThemeChanged: 'Theme wurde auf {value} umgestellt.',
    cmdModeChanged: 'Darstellung wurde auf {value} gesetzt.',
    cmdMotionChanged: 'Bewegungsstil wurde auf {value} umgestellt.',
    modeDark: 'Dunkel',
    modeLight: 'Hell',
    modeAuto: 'Automatisch',
    tabConfig: 'Konfiguration',
    tabIndexing: 'Indexierung',
    tabSources: 'Quellen',
    tabDesign: 'Design',
    aiModel: 'KI-Modell',
    protocol: 'Protokoll',
    host: 'Host',
    port: 'Port',
    model: 'Modell',
    selectModel: 'Modell auswählen...',
    suggestions: 'Vorschläge',
    personalizedSuggestions: 'Personalisierte Vorschläge basierend auf deinem Nutzungsverhalten',
    authSettings: 'Authentifizierung',
    allowRegistration: 'Registrierung erlauben',
    requireLogin: 'Anmeldung erforderlich',
    userManagement: 'Benutzerverwaltung',
    createNewUser: 'Neuen Benutzer anlegen',
    deleteUser: 'Löschen',
    userDeleted: 'Benutzer gelöscht',
    userCreated: 'Benutzer angelegt',
    passwordReset: 'Passwort zurückgesetzt',
    adminTab: 'Admin'
  },
  en: {
    newChat: 'New Chat',
    settings: 'Settings',
    currentChat: 'Current Chat',
    askHeading: 'What is on your mind?',
    askSubheading: 'Ask anything about your knowledge base.',
    askPlaceholder: 'Ask a question...',
    composerPlaceholder: 'Your message here...',
    documentIndexing: 'Document Indexing',
    current: 'Current',
    files: 'Files',
    speed: 'Speed',
    elapsed: 'Elapsed',
    chunks: 'Chunks',
    errors: 'Errors',
    save: 'Save',
    cancel: 'Cancel',
    createEvent: 'Create event',
    saveEvent: 'Saving...',
    sources: 'Sources',
    language: 'Language',
    theme: 'Theme',
    darkMode: 'Dark Mode',
    motionStyle: 'Motion Style',
    motionCalm: 'Calm',
    motionDynamic: 'Dynamic',
    motionAurora: 'Aurora',
    designControlHint: 'You can adjust design options directly here:',
    cmdLanguageChanged: 'Language was switched to {value}.',
    cmdThemeChanged: 'Theme was switched to {value}.',
    cmdModeChanged: 'Appearance was switched to {value}.',
    cmdMotionChanged: 'Motion style was switched to {value}.',
    modeDark: 'Dark',
    modeLight: 'Light',
    modeAuto: 'Auto',
    tabConfig: 'Config',
    tabIndexing: 'Indexing',
    tabSources: 'Sources',
    tabDesign: 'Design',
    aiModel: 'AI Model',
    protocol: 'Protocol',
    host: 'Host',
    port: 'Port',
    model: 'Model',
    selectModel: 'Select model...',
    suggestions: 'Suggestions',
    personalizedSuggestions: 'Personalized suggestions based on your usage patterns',
    authSettings: 'Authentication',
    allowRegistration: 'Allow registration',
    requireLogin: 'Login required',
    userManagement: 'User Management',
    createNewUser: 'Create new user',
    deleteUser: 'Delete',
    userDeleted: 'User deleted',
    userCreated: 'User created',
    passwordReset: 'Password reset',
    adminTab: 'Admin'
  },
  fr: {
    newChat: 'Nouveau Chat',
    settings: 'Paramètres',
    currentChat: 'Chat Actuel',
    askHeading: 'Qu\'avez-vous en tête?',
    askSubheading: 'Posez n\'importe quelle question sur votre base de connaissances.',
    askPlaceholder: 'Poser une question...',
    composerPlaceholder: 'Votre message ici...',
    documentIndexing: 'Indexation des Documents',
    current: 'Actuel',
    files: 'Fichiers',
    speed: 'Vitesse',
    elapsed: 'Écoulé',
    chunks: 'Morceaux',
    errors: 'Erreurs',
    save: 'Enregistrer',
    cancel: 'Annuler',
    createEvent: 'Créer un événement',
    saveEvent: 'Enregistrement...',
    sources: 'Sources',
    language: 'Langue',
    theme: 'Thème',
    darkMode: 'Mode Sombre',
    cmdLanguageChanged: 'La langue a été changée en {value}.',
    cmdThemeChanged: 'Le thème a été changé en {value}.',
    cmdModeChanged: 'L\'apparence a été changée en {value}.',
    modeDark: 'Sombre',
    modeLight: 'Clair',
    modeAuto: 'Auto',
    tabConfig: 'Configuration',
    tabIndexing: 'Indexation',
    tabSources: 'Sources',
    tabDesign: 'Design',
    aiModel: 'Modèle IA',
    protocol: 'Protocole',
    host: 'Hôte',
    port: 'Port',
    model: 'Modèle',
    selectModel: 'Sélectionner un modèle...',
    suggestions: 'Suggestions',
    personalizedSuggestions: 'Suggestions personnalisées basées sur vos habitudes d\'utilisation',
    authSettings: 'Authentification',
    allowRegistration: 'Autoriser l\'inscription',
    requireLogin: 'Connexion requise',
    userManagement: 'Gestion des utilisateurs',
    createNewUser: 'Créer un utilisateur',
    deleteUser: 'Supprimer',
    userDeleted: 'Utilisateur supprimé',
    userCreated: 'Utilisateur créé',
    passwordReset: 'Mot de passe réinitialisé',
    adminTab: 'Admin'
  },
  es: {
    newChat: 'Nuevo Chat',
    settings: 'Configuración',
    currentChat: 'Chat Actual',
    askHeading: '¿Qué tienes en mente?',
    askSubheading: 'Pregunta lo que quieras sobre tu base de conocimiento.',
    askPlaceholder: 'Hacer una pregunta...',
    composerPlaceholder: 'Tu mensaje aquí...',
    documentIndexing: 'Indexación de Documentos',
    current: 'Actual',
    files: 'Archivos',
    speed: 'Velocidad',
    elapsed: 'Transcurrido',
    chunks: 'Fragmentos',
    errors: 'Errores',
    save: 'Guardar',
    cancel: 'Cancelar',
    createEvent: 'Crear evento',
    saveEvent: 'Guardando...',
    sources: 'Fuentes',
    language: 'Idioma',
    theme: 'Tema',
    darkMode: 'Modo Oscuro',
    cmdLanguageChanged: 'El idioma se cambió a {value}.',
    cmdThemeChanged: 'El tema se cambió a {value}.',
    cmdModeChanged: 'La apariencia se cambió a {value}.',
    modeDark: 'Oscuro',
    modeLight: 'Claro',
    modeAuto: 'Auto',
    tabConfig: 'Configuración',
    tabIndexing: 'Indexación',
    tabSources: 'Fuentes',
    tabDesign: 'Diseño',
    aiModel: 'Modelo IA',
    protocol: 'Protocolo',
    host: 'Host',
    port: 'Puerto',
    model: 'Modelo',
    selectModel: 'Seleccionar modelo...',
    suggestions: 'Sugerencias',
    personalizedSuggestions: 'Sugerencias personalizadas basadas en tus patrones de uso',
    authSettings: 'Autenticación',
    allowRegistration: 'Permitir registro',
    requireLogin: 'Inicio de sesión requerido',
    userManagement: 'Gestión de usuarios',
    createNewUser: 'Crear nuevo usuario',
    deleteUser: 'Eliminar',
    userDeleted: 'Usuario eliminado',
    userCreated: 'Usuario creado',
    passwordReset: 'Contraseña restablecida',
    adminTab: 'Admin'
  },
  it: {
    newChat: 'Nuova Chat',
    settings: 'Impostazioni',
    currentChat: 'Chat Corrente',
    askHeading: 'Cosa hai in mente?',
    askSubheading: 'Chiedi qualsiasi cosa sulla tua base di conoscenza.',
    askPlaceholder: 'Fai una domanda...',
    composerPlaceholder: 'Il tuo messaggio qui...',
    documentIndexing: 'Indicizzazione Documenti',
    current: 'Corrente',
    files: 'File',
    speed: 'Velocità',
    elapsed: 'Trascorso',
    chunks: 'Frammenti',
    errors: 'Errori',
    save: 'Salva',
    cancel: 'Annulla',
    createEvent: 'Crea evento',
    saveEvent: 'Salvataggio...',
    sources: 'Fonti',
    language: 'Lingua',
    theme: 'Tema',
    darkMode: 'Modalità Scura',
    cmdLanguageChanged: 'La lingua è stata cambiata in {value}.',
    cmdThemeChanged: 'Il tema è stato cambiato in {value}.',
    cmdModeChanged: 'L\'aspetto è stato cambiato in {value}.',
    modeDark: 'Scuro',
    modeLight: 'Chiaro',
    modeAuto: 'Auto',
    tabConfig: 'Configurazione',
    tabIndexing: 'Indicizzazione',
    tabSources: 'Fonti',
    tabDesign: 'Design',
    aiModel: 'Modello IA',
    protocol: 'Protocollo',
    host: 'Host',
    port: 'Porta',
    model: 'Modello',
    selectModel: 'Seleziona modello...',
    suggestions: 'Suggerimenti',
    personalizedSuggestions: 'Suggerimenti personalizzati basati sui tuoi modelli di utilizzo',
    authSettings: 'Autenticazione',
    allowRegistration: 'Consenti registrazione',
    requireLogin: 'Accesso richiesto',
    userManagement: 'Gestione utenti',
    createNewUser: 'Crea nuovo utente',
    deleteUser: 'Elimina',
    userDeleted: 'Utente eliminato',
    userCreated: 'Utente creato',
    passwordReset: 'Password reimpostata',
    adminTab: 'Admin'
  },
  pt: {
    newChat: 'Novo Chat',
    settings: 'Configurações',
    currentChat: 'Chat Atual',
    askHeading: 'O que está em sua mente?',
    askSubheading: 'Pergunte qualquer coisa sobre sua base de conhecimento.',
    askPlaceholder: 'Faça uma pergunta...',
    composerPlaceholder: 'Sua mensagem aqui...',
    documentIndexing: 'Indexação de Documentos',
    current: 'Atual',
    files: 'Arquivos',
    speed: 'Velocidade',
    elapsed: 'Decorrido',
    chunks: 'Fragmentos',
    errors: 'Erros',
    save: 'Salvar',
    cancel: 'Cancelar',
    createEvent: 'Criar evento',
    saveEvent: 'Salvando...',
    sources: 'Fontes',
    language: 'Idioma',
    theme: 'Tema',
    darkMode: 'Modo Escuro',
    cmdLanguageChanged: 'O idioma foi alterado para {value}.',
    cmdThemeChanged: 'O tema foi alterado para {value}.',
    cmdModeChanged: 'A aparência foi alterada para {value}.',
    modeDark: 'Escuro',
    modeLight: 'Claro',
    modeAuto: 'Auto',
    tabConfig: 'Configuração',
    tabIndexing: 'Indexação',
    tabSources: 'Fontes',
    tabDesign: 'Design',
    aiModel: 'Modelo IA',
    protocol: 'Protocolo',
    host: 'Host',
    port: 'Porta',
    model: 'Modelo',
    selectModel: 'Selecionar modelo...',
    suggestions: 'Sugestões',
    personalizedSuggestions: 'Sugestões personalizadas com base em seus padrões de uso',
    authSettings: 'Autenticação',
    allowRegistration: 'Permitir registro',
    requireLogin: 'Login obrigatório',
    userManagement: 'Gerenciamento de usuários',
    createNewUser: 'Criar novo usuário',
    deleteUser: 'Excluir',
    userDeleted: 'Usuário excluído',
    userCreated: 'Usuário criado',
    passwordReset: 'Senha redefinida',
    adminTab: 'Admin'
  },
  nl: {
    newChat: 'Nieuwe Chat',
    settings: 'Instellingen',
    currentChat: 'Huidige Chat',
    askHeading: 'Wat houdt je bezig?',
    askSubheading: 'Vraag alles over je kennisbank.',
    askPlaceholder: 'Stel een vraag...',
    composerPlaceholder: 'Je bericht hier...',
    documentIndexing: 'Document Indexering',
    current: 'Huidig',
    files: 'Bestanden',
    speed: 'Snelheid',
    elapsed: 'Verstreken',
    chunks: 'Fragmenten',
    errors: 'Fouten',
    save: 'Opslaan',
    cancel: 'Annuleren',
    createEvent: 'Gebeurtenis maken',
    saveEvent: 'Opslaan...',
    sources: 'Bronnen',
    language: 'Taal',
    theme: 'Thema',
    darkMode: 'Donkere Modus',
    cmdLanguageChanged: 'Taal is gewijzigd naar {value}.',
    cmdThemeChanged: 'Thema is gewijzigd naar {value}.',
    cmdModeChanged: 'Uiterlijk is gewijzigd naar {value}.',
    modeDark: 'Donker',
    modeLight: 'Licht',
    modeAuto: 'Auto',
    tabConfig: 'Configuratie',
    tabIndexing: 'Indexering',
    tabSources: 'Bronnen',
    tabDesign: 'Ontwerp',
    aiModel: 'AI Model',
    protocol: 'Protocol',
    host: 'Host',
    port: 'Poort',
    model: 'Model',
    selectModel: 'Model selecteren...',
    suggestions: 'Suggesties',
    personalizedSuggestions: 'Gepersonaliseerde suggesties op basis van je gebruikspatronen',
    authSettings: 'Authenticatie',
    allowRegistration: 'Registratie toestaan',
    requireLogin: 'Inloggen vereist',
    userManagement: 'Gebruikersbeheer',
    createNewUser: 'Nieuwe gebruiker aanmaken',
    deleteUser: 'Verwijderen',
    userDeleted: 'Gebruiker verwijderd',
    userCreated: 'Gebruiker aangemaakt',
    passwordReset: 'Wachtwoord gereset',
    adminTab: 'Admin'
  },
  pl: {
    newChat: 'Nowy Chat',
    settings: 'Ustawienia',
    currentChat: 'Bieżący Chat',
    askHeading: 'Co Cię nurtuje?',
    askSubheading: 'Zapytaj o cokolwiek z Twojej bazy wiedzy.',
    askPlaceholder: 'Zadaj pytanie...',
    composerPlaceholder: 'Twoja wiadomość tutaj...',
    documentIndexing: 'Indeksowanie Dokumentów',
    current: 'Bieżący',
    files: 'Pliki',
    speed: 'Prędkość',
    elapsed: 'Upłynęło',
    chunks: 'Fragmenty',
    errors: 'Błędy',
    save: 'Zapisz',
    cancel: 'Anuluj',
    createEvent: 'Utwórz wydarzenie',
    saveEvent: 'Zapisywanie...',
    sources: 'Źródła',
    language: 'Język',
    theme: 'Motyw',
    darkMode: 'Tryb Ciemny',
    cmdLanguageChanged: 'Język został zmieniony na {value}.',
    cmdThemeChanged: 'Motyw został zmieniony na {value}.',
    cmdModeChanged: 'Wygląd został zmieniony na {value}.',
    modeDark: 'Ciemny',
    modeLight: 'Jasny',
    modeAuto: 'Auto',
    tabConfig: 'Konfiguracja',
    tabIndexing: 'Indeksowanie',
    tabSources: 'Źródła',
    tabDesign: 'Design',
    aiModel: 'Model AI',
    protocol: 'Protokół',
    host: 'Host',
    port: 'Port',
    model: 'Model',
    selectModel: 'Wybierz model...',
    suggestions: 'Sugestie',
    personalizedSuggestions: 'Spersonalizowane sugestie oparte na Twoich wzorcach użytkowania',
    authSettings: 'Uwierzytelnianie',
    allowRegistration: 'Zezwól na rejestrację',
    requireLogin: 'Wymagane logowanie',
    userManagement: 'Zarządzanie użytkownikami',
    createNewUser: 'Utwórz nowego użytkownika',
    deleteUser: 'Usuń',
    userDeleted: 'Użytkownik usunięty',
    userCreated: 'Użytkownik utworzony',
    passwordReset: 'Hasło zresetowane',
    adminTab: 'Admin'
  },
  tr: {
    newChat: 'Yeni Sohbet',
    settings: 'Ayarlar',
    currentChat: 'Mevcut Sohbet',
    askHeading: 'Aklında ne var?',
    askSubheading: 'Bilgi tabanın hakkında her şeyi sor.',
    askPlaceholder: 'Bir soru sor...',
    composerPlaceholder: 'Mesajınız burada...',
    documentIndexing: 'Belge Dizinleme',
    current: 'Mevcut',
    files: 'Dosyalar',
    speed: 'Hız',
    elapsed: 'Geçen',
    chunks: 'Parçalar',
    errors: 'Hatalar',
    save: 'Kaydet',
    cancel: 'İptal',
    createEvent: 'Etkinlik oluştur',
    saveEvent: 'Kaydediliyor...',
    sources: 'Kaynaklar',
    language: 'Dil',
    theme: 'Tema',
    darkMode: 'Karanlık Mod',
    cmdLanguageChanged: 'Dil {value} olarak değiştirildi.',
    cmdThemeChanged: 'Tema {value} olarak değiştirildi.',
    cmdModeChanged: 'Görünüm {value} olarak değiştirildi.',
    modeDark: 'Karanlık',
    modeLight: 'Aydınlık',
    modeAuto: 'Otomatik',
    tabConfig: 'Yapılandırma',
    tabIndexing: 'Dizinleme',
    tabSources: 'Kaynaklar',
    tabDesign: 'Tasarım',
    aiModel: 'AI Modeli',
    protocol: 'Protokol',
    host: 'Sunucu',
    port: 'Port',
    model: 'Model',
    selectModel: 'Model seç...',
    suggestions: 'Öneriler',
    personalizedSuggestions: 'Kullanım alışkanlıklarınıza göre kişiselleştirilmiş öneriler',
    authSettings: 'Kimlik Doğrulama',
    allowRegistration: 'Kayıt izni',
    requireLogin: 'Giriş zorunlu',
    userManagement: 'Kullanıcı Yönetimi',
    createNewUser: 'Yeni kullanıcı oluştur',
    deleteUser: 'Sil',
    userDeleted: 'Kullanıcı silindi',
    userCreated: 'Kullanıcı oluşturuldu',
    passwordReset: 'Şifre sıfırlandı',
    adminTab: 'Yönetici'
  },
  ru: {
    newChat: 'Новый Чат',
    settings: 'Настройки',
    currentChat: 'Текущий Чат',
    askHeading: 'Что у вас на уме?',
    askSubheading: 'Спросите что угодно о вашей базе знаний.',
    askPlaceholder: 'Задать вопрос...',
    composerPlaceholder: 'Ваше сообщение здесь...',
    documentIndexing: 'Индексация Документов',
    current: 'Текущий',
    files: 'Файлы',
    speed: 'Скорость',
    elapsed: 'Прошло',
    chunks: 'Фрагменты',
    errors: 'Ошибки',
    save: 'Сохранить',
    cancel: 'Отмена',
    createEvent: 'Создать событие',
    saveEvent: 'Сохранение...',
    sources: 'Источники',
    language: 'Язык',
    theme: 'Тема',
    darkMode: 'Темный Режим',
    cmdLanguageChanged: 'Язык изменен на {value}.',
    cmdThemeChanged: 'Тема изменена на {value}.',
    cmdModeChanged: 'Внешний вид изменен на {value}.',
    modeDark: 'Темный',
    modeLight: 'Светлый',
    modeAuto: 'Авто',
    tabConfig: 'Конфигурация',
    tabIndexing: 'Индексация',
    tabSources: 'Источники',
    tabDesign: 'Дизайн',
    aiModel: 'AI Модель',
    protocol: 'Протокол',
    host: 'Хост',
    port: 'Порт',
    model: 'Модель',
    selectModel: 'Выбрать модель...',
    suggestions: 'Предложения',
    personalizedSuggestions: 'Персонализированные предложения на основе ваших шаблонов использования',
    authSettings: 'Аутентификация',
    allowRegistration: 'Разрешить регистрацию',
    requireLogin: 'Требуется вход',
    userManagement: 'Управление пользователями',
    createNewUser: 'Создать пользователя',
    deleteUser: 'Удалить',
    userDeleted: 'Пользователь удален',
    userCreated: 'Пользователь создан',
    passwordReset: 'Пароль сброшен',
    adminTab: 'Админ'
  },
  ja: {
    newChat: '新しいチャット',
    settings: '設定',
    currentChat: '現在のチャット',
    askHeading: '何をお考えですか？',
    askSubheading: 'ナレッジベースについて何でも聞いてください。',
    askPlaceholder: '質問してください...',
    composerPlaceholder: 'ここにメッセージを...',
    documentIndexing: 'ドキュメントのインデックス作成',
    current: '現在',
    files: 'ファイル',
    speed: '速度',
    elapsed: '経過時間',
    chunks: 'チャンク',
    errors: 'エラー',
    save: '保存',
    cancel: 'キャンセル',
    createEvent: 'イベントを作成',
    saveEvent: '保存中...',
    sources: 'ソース',
    language: '言語',
    theme: 'テーマ',
    darkMode: 'ダークモード',
    cmdLanguageChanged: '言語が{value}に変更されました。',
    cmdThemeChanged: 'テーマが{value}に変更されました。',
    cmdModeChanged: '外観が{value}に変更されました。',
    modeDark: 'ダーク',
    modeLight: 'ライト',
    modeAuto: '自動',
    tabConfig: '設定',
    tabIndexing: 'インデックス',
    tabSources: 'ソース',
    tabDesign: 'デザイン',
    aiModel: 'AIモデル',
    protocol: 'プロトコル',
    host: 'ホスト',
    port: 'ポート',
    model: 'モデル',
    selectModel: 'モデルを選択...',
    suggestions: '提案',
    personalizedSuggestions: '使用パターンに基づいたパーソナライズされた提案',
    authSettings: '認証',
    allowRegistration: '登録を許可',
    requireLogin: 'ログインが必要',
    userManagement: 'ユーザー管理',
    createNewUser: '新規ユーザー作成',
    deleteUser: '削除',
    userDeleted: 'ユーザーを削除しました',
    userCreated: 'ユーザーを作成しました',
    passwordReset: 'パスワードをリセットしました',
    adminTab: '管理'
  },
  zh: {
    newChat: '新聊天',
    settings: '设置',
    currentChat: '当前聊天',
    askHeading: '你在想什么？',
    askSubheading: '询问有关您的知识库的任何内容。',
    askPlaceholder: '提问...',
    composerPlaceholder: '在这里输入您的消息...',
    documentIndexing: '文档索引',
    current: '当前',
    files: '文件',
    speed: '速度',
    elapsed: '已用时间',
    chunks: '块',
    errors: '错误',
    save: '保存',
    cancel: '取消',
    createEvent: '创建事件',
    saveEvent: '保存中...',
    sources: '来源',
    language: '语言',
    theme: '主题',
    darkMode: '深色模式',
    cmdLanguageChanged: '语言已切换至{value}。',
    cmdThemeChanged: '主题已切换至{value}。',
    cmdModeChanged: '外观已切换至{value}。',
    modeDark: '深色',
    modeLight: '浅色',
    modeAuto: '自动',
    tabConfig: '配置',
    tabIndexing: '索引',
    tabSources: '来源',
    tabDesign: '设计',
    aiModel: 'AI模型',
    protocol: '协议',
    host: '主机',
    port: '端口',
    model: '模型',
    selectModel: '选择模型...',
    suggestions: '建议',
    personalizedSuggestions: '基于您的使用模式的个性化建议',
    authSettings: '身份验证',
    allowRegistration: '允许注册',
    requireLogin: '需要登录',
    userManagement: '用户管理',
    createNewUser: '创建新用户',
    deleteUser: '删除',
    userDeleted: '用户已删除',
    userCreated: '用户已创建',
    passwordReset: '密码已重置',
    adminTab: '管理'
  }
};

function interpolate(template, vars) {
  return String(template).replace(/\{(\w+)\}/g, (_, key) => vars?.[key] ?? `{${key}}`);
}

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState('de');

  useEffect(() => {
    const stored = localStorage.getItem(LANGUAGE_STORAGE_KEY);
    const valid = SUPPORTED_LANGUAGES.some((l) => l.code === stored);
    const next = valid ? stored : 'de';
    setLanguageState(next);
    document.documentElement.setAttribute('lang', next);
  }, []);

  const setLanguage = useCallback((nextLanguage) => {
    const valid = SUPPORTED_LANGUAGES.some((l) => l.code === nextLanguage);
    const safe = valid ? nextLanguage : 'de';
    setLanguageState(safe);
    localStorage.setItem(LANGUAGE_STORAGE_KEY, safe);
    document.documentElement.setAttribute('lang', safe);
  }, []);

  const value = useMemo(() => ({ language, setLanguage }), [language, setLanguage]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');

  const { language, setLanguage } = ctx;

  const t = useMemo(() => {
    return (key, vars) => {
      const table = TRANSLATIONS[language] || TRANSLATIONS.en;
      const value = table?.[key] ?? TRANSLATIONS.de[key] ?? key;
      return interpolate(value, vars);
    };
  }, [language]);

  return {
    language,
    setLanguage,
    t,
    languages: SUPPORTED_LANGUAGES
  };
}
