#!/usr/bin/env python3
"""
Setup script for MYND environment configuration.
Creates a secure .env file with proper permissions.

Usage:
    python3 setup_env.py
"""

import os
import sys
from pathlib import Path
from getpass import getpass
import json

def safe_write_env(filepath: str, data: dict) -> None:
    """Write .env file with restrictive permissions (600)."""
    # Create content
    lines = ["# MYND Environment Configuration"]
    lines.append("# Auto-generated by setup_env.py")
    lines.append("# DO NOT COMMIT TO GIT!")
    lines.append("")
    
    for key, value in data.items():
        if value:
            # Quote values with spaces
            if ' ' in str(value):
                lines.append(f'{key}="{value}"')
            else:
                lines.append(f'{key}={value}')
        else:
            lines.append(f'# {key}=')
    
    content = '\n'.join(lines)
    
    # Write atomically
    tmp_file = f"{filepath}.tmp"
    try:
        with open(tmp_file, 'w', encoding='utf-8') as f:
            f.write(content)
        
        # Set restrictive permissions (owner read/write only)
        os.chmod(tmp_file, 0o600)
        
        # Atomic replace
        os.replace(tmp_file, filepath)
        print(f"✅ Created {filepath} with permissions 600")
    except Exception as e:
        print(f"❌ Error writing {filepath}: {e}")
        if os.path.exists(tmp_file):
            os.remove(tmp_file)
        sys.exit(1)

def prompt_optional(prompt_text: str, default: str = "") -> str:
    """Prompt user for optional input."""
    full_prompt = f"{prompt_text}"
    if default:
        full_prompt += f" [{default}]"
    full_prompt += ": "
    
    value = input(full_prompt).strip()
    return value or default

def prompt_secret(prompt_text: str) -> str:
    """Prompt user for secret/password input (masked)."""
    return getpass(f"{prompt_text}: ").strip()

def main():
    root_dir = Path(__file__).parent
    env_file = root_dir / ".env"
    
    print("=" * 60)
    print("🔐 MYND Environment Setup")
    print("=" * 60)
    print()
    
    # Check if .env already exists
    if env_file.exists():
        response = input(f"⚠️  {env_file} already exists. Overwrite? (y/n): ").strip().lower()
        if response != 'y':
            print("Aborted.")
            return
    
    print()
    print("This setup will create a secure .env file with your configuration.")
    print("Sensitive values will NOT be displayed.")
    print()
    
    env_data = {}
    
    # Backend
    print("--- BACKEND Configuration ---")
    env_data['BACKEND_HOST'] = prompt_optional("Backend Host", "0.0.0.0")
    env_data['BACKEND_PORT'] = prompt_optional("Backend Port", "5000")
    env_data['FLASK_ENV'] = prompt_optional("Flask Environment (development/production)", "development")
    env_data['DEBUG'] = prompt_optional("Debug Mode (true/false)", "false")
    
    print()
    print("--- Ollama Configuration ---")
    env_data['OLLAMA_BASE_URL'] = prompt_optional(
        "Ollama Base URL",
        "http://localhost:11434"
    )
    env_data['OLLAMA_MODEL'] = prompt_optional("Ollama Model", "gemma2:latest")
    
    print()
    print("--- Immich Integration (optional) ---")
    immich_enabled = prompt_optional("Enable Immich? (y/n)", "n").lower() == 'y'
    if immich_enabled:
        env_data['IMMICH_URL'] = prompt_optional("Immich URL (e.g., https://fotos.example.com)", "")
        if env_data['IMMICH_URL']:
            env_data['IMMICH_API_KEY'] = prompt_secret("Immich API Key")
    
    print()
    print("--- Nextcloud Integration (optional) ---")
    nc_enabled = prompt_optional("Enable Nextcloud? (y/n)", "n").lower() == 'y'
    if nc_enabled:
        env_data['NEXTCLOUD_URL'] = prompt_optional("Nextcloud URL (e.g., https://cloud.example.com)", "")
        if env_data['NEXTCLOUD_URL']:
            env_data['NEXTCLOUD_USERNAME'] = prompt_optional("Nextcloud Username", "")
            env_data['NEXTCLOUD_PASSWORD'] = prompt_secret("Nextcloud Password")
            env_data['NEXTCLOUD_DISPLAY_NAME'] = prompt_optional("Display Name", "MYND")
    
    print()
    print("--- OpenWeather Integration (optional) ---")
    weather_enabled = prompt_optional("Enable OpenWeather? (y/n)", "n").lower() == 'y'
    if weather_enabled:
        env_data['OPENWEATHER_API_KEY'] = prompt_secret("OpenWeather API Key")
    
    print()
    print("--- Frontend Configuration ---")
    env_data['NEXT_PUBLIC_API_URL'] = prompt_optional(
        "Frontend API URL",
        "http://localhost:5000"
    )
    env_data['NEXT_PUBLIC_APP_NAME'] = prompt_optional("App Name", "MYND")
    
    print()
    print("--- Security ---")
    env_data['JWT_SECRET'] = prompt_optional(
        "JWT Secret (leave empty to auto-generate)",
        ""
    )
    env_data['SESSION_SECRET'] = prompt_optional(
        "Session Secret (leave empty to auto-generate)",
        ""
    )
    env_data['CORS_ORIGINS'] = prompt_optional(
        "CORS Origins (comma-separated)",
        "http://localhost:3000"
    )
    
    # Write file
    print()
    safe_write_env(str(env_file), env_data)
    
    print()
    print("=" * 60)
    print("✅ Setup complete!")
    print("=" * 60)
    print()
    print("📝 Next steps:")
    print(f"  1. Review {env_file}")
    print("  2. Start backend:  cd backend/core && python3 app.py")
    print("  3. Start frontend: cd frontend && npm run dev")
    print()
    print("⚠️  Remember:")
    print("  • .env is in .gitignore - NEVER commit it")
    print("  • Use .env.example as template for other developers")
    print()

if __name__ == "__main__":
    main()
